<?xml version="1.0" encoding="utf-8"?>
<Database Name="Repository" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="AlbumGenres">
    <Type Name="AlbumGenre">
      <Column Name="AlbumId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenreId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="FK_Albums_AlbumGenres" Member="Album" ThisKey="AlbumId" OtherKey="Id" Type="Album" IsForeignKey="true" />
      <Association Name="FK_Genres_AlbumGenres" Member="Genre" ThisKey="GenreId" OtherKey="Id" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Albums">
    <Type Name="Album">
      <Column Name="Name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="MBID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastFMListeners" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LastFMPlays" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ArtistId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="FK_Albums_AlbumGenres" Member="AlbumGenres" ThisKey="Id" OtherKey="AlbumId" Type="AlbumGenre" DeleteRule="NO ACTION" />
      <Association Name="FK_Albums_Tracks" Member="Tracks" ThisKey="Id" OtherKey="AlbumId" Type="Track" DeleteRule="NO ACTION" />
      <Association Name="FK_Artists_Albums" Member="Artist" ThisKey="ArtistId" OtherKey="Id" Type="Artist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ArtistGenres">
    <Type Name="ArtistGenre">
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenreId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ArtistId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_Artists_ArtistGenres" Member="Artist" ThisKey="ArtistId" OtherKey="Id" Type="Artist" IsForeignKey="true" />
      <Association Name="FK_Genres_ArtistGenres" Member="Genre" ThisKey="GenreId" OtherKey="Id" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Artists">
    <Type Name="Artist">
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MBID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastFMListeners" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LastFMPlays" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Bio" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_Artists_Albums" Member="Albums" ThisKey="Id" OtherKey="ArtistId" Type="Album" DeleteRule="NO ACTION" />
      <Association Name="FK_Artists_ArtistGenres" Member="ArtistGenres" ThisKey="Id" OtherKey="ArtistId" Type="ArtistGenre" DeleteRule="NO ACTION" />
      <Association Name="FK_Artists_Tracks" Member="Tracks" ThisKey="Id" OtherKey="ArtistId" Type="Track" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="Genres">
    <Type Name="Genre">
      <Column Name="Name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_Genres_AlbumGenres" Member="AlbumGenres" ThisKey="Id" OtherKey="GenreId" Type="AlbumGenre" DeleteRule="NO ACTION" />
      <Association Name="FK_Genres_ArtistGenres" Member="ArtistGenres" ThisKey="Id" OtherKey="GenreId" Type="ArtistGenre" DeleteRule="NO ACTION" />
      <Association Name="FK_Genres_TrackGenres" Member="TrackGenres" ThisKey="Id" OtherKey="GenreId" Type="TrackGenre" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="MediaFiles">
    <Type Name="MediaFile">
      <Column Name="FullPath" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FileType" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrackId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RepositoryId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="FK_MediaFiles_Tracks" Member="Tracks" ThisKey="Id" OtherKey="MediaFileId" Type="Track" DeleteRule="NO ACTION" />
      <Association Name="FK_MediaRepositories_MediaFiles" Member="MediaRepository" ThisKey="RepositoryId" OtherKey="Id" Type="MediaRepository" IsForeignKey="true" />
      <Association Name="FK_Tracks_MediaFiles" Member="Track" ThisKey="TrackId" OtherKey="Id" Type="Track" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="MediaRepositories">
    <Type Name="MediaRepository">
      <Column Name="Location" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastScanned" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_MediaRepositories_MediaFiles" Member="MediaFiles" ThisKey="Id" OtherKey="RepositoryId" Type="MediaFile" DeleteRule="NO ACTION" />
    </Type>
  </Table>
  <Table Name="Plays">
    <Type Name="Play">
      <Column Name="DatePlayed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Percentage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrackId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="FK_Tracks_Plays" Member="Track" ThisKey="TrackId" OtherKey="Id" Type="Track" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SimilarAlbums">
    <Type Name="SimilarAlbum">
      <Column Name="Score" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="AlbumId_1" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AlbumId_2" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="SimilarArtists">
    <Type Name="SimilarArtist">
      <Column Name="Score" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ArtistId_1" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ArtistId_2" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="SimilarTracks">
    <Type Name="SimilarTrack">
      <Column Name="Score" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="TrackId_1" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TrackId_2" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="TrackGenres">
    <Type Name="TrackGenre">
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrackId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GenreId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="FK_Genres_TrackGenres" Member="Genre" ThisKey="GenreId" OtherKey="Id" Type="Genre" IsForeignKey="true" />
      <Association Name="FK_Tracks_TrackGenres" Member="Track" ThisKey="TrackId" OtherKey="Id" Type="Track" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Tracks">
    <Type Name="Track">
      <Column Name="Name" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="TrackNumber" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BPM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BitRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Composer" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="DiscNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SampleRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MBID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LastFMListeners" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LastFMPlays" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Rating" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ArtistId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="AlbumId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="MediaFileId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="FK_Albums_Tracks" Member="Album" ThisKey="AlbumId" OtherKey="Id" Type="Album" IsForeignKey="true" />
      <Association Name="FK_Artists_Tracks" Member="Artist" ThisKey="ArtistId" OtherKey="Id" Type="Artist" IsForeignKey="true" />
      <Association Name="FK_MediaFiles_Tracks" Member="MediaFile" ThisKey="MediaFileId" OtherKey="Id" Type="MediaFile" IsForeignKey="true" />
      <Association Name="FK_Tracks_MediaFiles" Member="MediaFiles" ThisKey="Id" OtherKey="TrackId" Type="MediaFile" DeleteRule="NO ACTION" />
      <Association Name="FK_Tracks_Plays" Member="Plays" ThisKey="Id" OtherKey="TrackId" Type="Play" DeleteRule="NO ACTION" />
      <Association Name="FK_Tracks_TrackGenres" Member="TrackGenres" ThisKey="Id" OtherKey="TrackId" Type="TrackGenre" DeleteRule="NO ACTION" />
    </Type>
  </Table>
</Database>